# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XW4EoQowxrwt8LCO9XkyAp_Uj3uQsAwV
"""



# FASTA File Reader + Sequence Analysis

# Open FASTA file
with open("sample.fasta", "r") as file:
    lines = file.readlines()

# Extract sequence name
sequence_name = lines[0].strip()

# Extract DNA sequence
dna = "".join(line.strip() for line in lines[1:]).upper()

# Count bases
a_count = dna.count("A")
t_count = dna.count("T")
g_count = dna.count("G")
c_count = dna.count("C")

# Total length
total_length = len(dna)

# GC Content
gc_content = ((g_count + c_count) / total_length) * 100

# Output
print("Sequence Name:", sequence_name)
print("DNA Sequence:", dna)
print("Total Length:", total_length)
print("A Count:", a_count)
print("T Count:", t_count)
print("G Count:", g_count)
print("C Count:", c_count)
print("GC Content:", round(gc_content, 2), "%")

